---
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
